import { test, expect } from '@playwright/test'
import { makeFixture } from '../../src/services/fixtures.js'

async function start(page, name = '온기 식탁') {
  await page.goto('/')
  await page.getByRole('button', { name: '데모 매장 찾기', exact: true }).click()
  await expect(page.locator('.entity-row')).toHaveCount(3)
  await page.locator('.entity-row', { hasText: name }).click()
}
const editor = page => page.getByRole('dialog', { name: /매장 사실 보완|제안 수정 요청/, exact: true })
async function scenario(page, value) {
  const dialog = editor(page)
  await dialog.getByText('데모 검증 설정', { exact: true }).click()
  await dialog.getByLabel('변경 응답 시나리오').selectOption(value)
}
async function setTheme(page, name, scope = page) {
  await scope.getByRole('button', { name: /화면 테마/ }).click()
  await page.getByRole('radio', { name: new RegExp(name) }).check()
  await page.getByRole('button', { name: '적용 완료' }).click()
}
test('standalone facts merge, empty validation, cancellation and exact target isolation', async ({ page }) => {
  const external = [], errors = []
  page.on('request', r => { if (!r.url().startsWith('http://127.0.0.1:5173')) external.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await start(page, '모퉁이 부엌')
  await page.getByRole('button', { name: '매장 사실 보완', exact: true }).click()
  let dialog = editor(page)
  await dialog.getByLabel('테이블 수 입력 방식').selectOption('value')
  await expect(dialog.getByText('테이블 수 값을 확인해 주세요.')).toBeVisible()
  await expect(dialog.getByRole('button', { name: '데모 사실 반영' })).toBeDisabled()
  await dialog.getByLabel('테이블 수', { exact: true }).fill('0')
  await dialog.getByLabel('인터넷 사용', { exact: true }).selectOption('false')
  await expect(dialog.getByRole('region', { name: '변경 전후 비교' })).toContainText('미확인 → 없음')
  await dialog.getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.getByRole('button', { name: '매장 사실 보완', exact: true })).toBeFocused()
  await expect(page.locator('.evidence-item')).toHaveCount(2)
  await page.getByRole('button', { name: '매장 사실 보완', exact: true }).click()
  dialog = editor(page)
  await expect(dialog.getByLabel('인터넷 사용', { exact: true })).toHaveValue('UNKNOWN')
  await dialog.getByLabel('테이블 수 입력 방식').selectOption('value')
  await dialog.getByLabel('테이블 수', { exact: true }).fill('0.5')
  await dialog.getByLabel('인터넷 사용', { exact: true }).selectOption('false')
  await dialog.getByRole('button', { name: '데모 사실 반영' }).dblclick()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.facts-grid')).toContainText('0.5')
  await expect(page.locator('.evidence-item')).toHaveCount(4)
  await expect(page.locator('.evidence-item', { hasText: '직원 확인' })).toHaveCount(2)
  await expect(page.locator('.detail-heading')).toContainText('확인 필요')
  await expect(page.locator('.evidence-content')).toContainText(['모퉁이 부엌', '모퉁이 분식', '0.5', '없음'])
  await page.locator('.entity-row', { hasText: '소담한' }).click()
  await expect(page.locator('.facts-grid > div', { hasText: '인터넷 사용' })).toContainText('미확인')
  expect(external).toEqual([]); expect(errors).toEqual([])
})
test('expression revision omits abandoned facts, preserves pending original, selects new and reads old', async ({ page }) => {
  await start(page)
  const original = await page.locator('.consultation-script').innerText()
  await page.getByRole('button', { name: '제안 수정 요청', exact: true }).click()
  const dialog = editor(page)
  await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).click()
  await expect(dialog.getByLabel('수정 사유 (필수)')).toBeFocused()
  await dialog.getByLabel('수정 방식').selectOption('facts')
  await dialog.getByLabel('테이블 수', { exact: true }).fill('0')
  await dialog.getByLabel('수정 방식').selectOption('expression')
  await dialog.getByLabel('수정 사유 (필수)').fill('질문형으로 짧게 바꿔 주세요.')
  await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).click()
  await expect(page.locator('.consultation-script')).toHaveText(original)
  await expect(dialog.getByRole('button', { name: '취소', exact: true })).toBeDisabled()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.proposal-preview')).toContainText('요청한 표현을 검토하기 위한')
  await expect(page.getByLabel('이번 세션의 제안')).toHaveValue(/-R1$/)
  await expect(page.locator('.facts-grid > div', { hasText: '테이블 수' })).toContainText('12')
  await expect(page.getByLabel('이번 세션의 제안').locator('option')).toHaveCount(2)
  await page.getByLabel('이번 세션의 제안').selectOption({ index: 1 })
  await expect(page.locator('.consultation-script')).toHaveText(original)
  await expect(page.locator('.proposal-preview').getByRole('button', { name: '제안 수정 요청', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '연결된 새 제안 보기' }).click()
  await expect(page.locator('.proposal-preview')).toContainText('직원 검토 대기')
  await expect(page.locator('.result-counts')).toContainText('초안 1')
})
test('facts revision links request provenance and marks Entity snapshot stale without a fake read', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: '제안 수정 요청', exact: true }).click()
  const dialog = editor(page)
  await dialog.getByLabel('수정 방식').selectOption('facts')
  await dialog.getByLabel('테이블 수', { exact: true }).fill('0')
  await dialog.getByLabel('인터넷 사용', { exact: true }).selectOption('UNKNOWN')
  await dialog.getByLabel('수정 사유 (필수)').fill('직원이 확인한 사실 반영')
  await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: '매장 사실 보완', exact: true })).toBeDisabled()
  await page.getByText('이 수정에 전달한 사실', { exact: true }).click()
  await expect(page.locator('.submitted-facts')).toContainText('테이블 수0인터넷 사용미확인')
  await expect(page.locator('.detail-panel')).toContainText('최신 Entity 조회가 연결되지 않아')
  await page.getByRole('button', { name: '제안 수정 요청', exact: true }).click()
  await expect(editor(page).getByLabel('수정 방식').locator('option[value=facts]')).toBeDisabled()
})
for (const [value, message] of [['noDraft', '새 초안이 없어요'], ['timeout', '처리 여부를 확인할 수 없어요'], ['stale', 'F05_INVALID_STATE'], ['missing', 'F05_PROPOSAL_NOT_FOUND'], ['invalid', 'CONTRACT_ERROR']]) {
  test(`revision ${value}: old state/input preserved, no repeat until supported recheck`, async ({ page }) => {
    await start(page)
    const original = await page.locator('.consultation-script').innerText()
    await page.getByRole('button', { name: '제안 수정 요청', exact: true }).click()
    const dialog = editor(page)
    await dialog.getByLabel('수정 사유 (필수)').fill('유지해야 할 입력')
    await scenario(page, value)
    await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).click()
    await expect(dialog.getByRole('alert')).toContainText(message)
    await expect(dialog.getByLabel('수정 사유 (필수)')).toHaveValue('유지해야 할 입력')
    await expect(dialog.getByRole('button', { name: '데모 수정 요청', exact: true })).toBeDisabled()
    await expect(page.locator('.consultation-script')).toHaveText(original)
    await expect(page.getByLabel('이번 세션의 제안').locator('option')).toHaveCount(1)
    await dialog.getByRole('button', { name: '입력 확인 후 닫기' }).click()
    await expect(page.getByRole('button', { name: '제안 수정 요청', exact: true })).toBeDisabled()
    await expect(page.locator('#entity-title')).toBeFocused()
    await expect(page.locator('.proposal-preview')).toContainText('직원 검토 대기')
  })
}
test('known fact failure keeps edits and original evidence; deliberate retry succeeds', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: '매장 사실 보완', exact: true }).click()
  const dialog = editor(page)
  await dialog.getByLabel('인터넷 사용', { exact: true }).selectOption('true')
  await scenario(page, 'error')
  await dialog.getByRole('button', { name: '데모 사실 반영' }).click()
  await expect(dialog.getByRole('alert')).toContainText('F02_STORED_JSON_INVALID')
  await expect(dialog.getByLabel('인터넷 사용', { exact: true })).toHaveValue('true')
  await expect(page.locator('.evidence-item')).toHaveCount(2)
  await dialog.getByLabel('변경 응답 시나리오').selectOption('success')
  await dialog.getByRole('button', { name: '데모 사실 반영' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.evidence-item')).toHaveCount(3)
})
test('approved revision allowed, rejected read only; untrusted text and fee 0/null render safely', async ({ page }) => {
  const conditions = { city: '서울특별시', district: '영등포구', startDate: '2026-10-01', endDate: '2026-10-03' }
  let state = 'APPROVED'
  await page.route('**/src/services/fixtures.js', route => {
    const raw = makeFixture('mixed', conditions)
    const proposal = raw[0].downstreamResults[0]
    proposal.proposalReviewState = state
    proposal.consultationScript = '<img src=x onerror=alert(1)> <script>alert(1)</script>'
    proposal.selectedProducts = [{ productName: '가상 상품', recommendationReason: '실제 가입 조건 아님', variants: [{ monthlyFee_0yr: null, monthlyFee_3yr: 0 }] }]
    return route.fulfill({ contentType: 'application/javascript', body: `export const SCENARIOS = [['mixed', '혼합']]; export function makeFixture() { return ${JSON.stringify(raw)} }` })
  })
  await start(page)
  await expect(page.locator('.consultation-script')).toContainText('<script>')
  await expect(page.locator('.consultation-script img')).toHaveCount(0)
  await expect(page.locator('.variant-fees')).toContainText('무약정: 미확인3년: 0원')
  await expect(page.getByRole('button', { name: '제안 수정 요청', exact: true })).toBeEnabled()
  state = 'REJECTED'; await start(page)
  await expect(page.getByRole('button', { name: '제안 수정 요청', exact: true })).toHaveCount(0)
})
for (const color of ['라이트', '다크']) for (const width of [390, 1440]) {
  test(`B ${color} ${width}px 200% text: modal, keyboard, theme preservation and success`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 1000 })
    await start(page)
    await setTheme(page, color)
    await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
    await page.getByRole('button', { name: '제안 수정 요청', exact: true }).click()
    const dialog = editor(page)
    await dialog.getByLabel('수정 방식').selectOption('facts')
    await dialog.getByLabel('인터넷 사용', { exact: true }).selectOption('UNKNOWN')
    await dialog.getByLabel('수정 사유 (필수)').fill('모바일과 테마 변경 후에도 입력 보존')
    await setTheme(page, color === '라이트' ? '다크' : '라이트', dialog)
    await expect(dialog.getByLabel('수정 사유 (필수)')).toHaveValue('모바일과 테마 변경 후에도 입력 보존')
    await setTheme(page, color, dialog)
    // Escape from nested theme dialog must return to the editor, not close it.
    await dialog.getByRole('button', { name: /화면 테마/ }).click()
    await page.keyboard.press('Escape')
    await expect(dialog).toBeVisible()
    await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).focus()
    await page.keyboard.press('Tab')
    await expect(dialog.getByRole('button', { name: /화면 테마/ })).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(dialog.getByRole('button', { name: '데모 수정 요청', exact: true })).toBeFocused()
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await dialog.getByLabel('테이블 수', { exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath('facts-editor.png') })
    await dialog.getByRole('button', { name: '데모 수정 요청', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await page.locator('.proposal-preview').scrollIntoViewIfNeeded()
    await expect(page.locator('.proposal-preview')).toContainText('직원 검토 대기')
    await page.screenshot({ path: testInfo.outputPath('proposal-revised.png') })
    if (width === 390) {
      await page.getByRole('button', { name: '← 전체 매장 목록으로' }).click()
      await expect(page.locator('.entity-row').first()).toBeFocused()
    }
  })
}
