export const PRODUCT_CATEGORIES = Object.freeze(['INTERNET', 'WIFI', 'POS', 'CCTV']);
export const ACTUAL_OPEN_STATUSES = Object.freeze(['OPEN', 'PREPARING', 'CLOSED', 'UNKNOWN']);
export const INSTALL_STATUSES = Object.freeze(['PASS', 'FAIL', 'UNKNOWN']);
export const CONTRACT_STATUSES = Object.freeze(['CONTRACTED', 'UNDECIDED', 'NOT_REQUIRED', 'UNKNOWN']);
export const LEAD_STATUSES = Object.freeze(['DISCOVERED', 'VERIFIED', 'READY', 'CONTACTED', 'FOLLOW_UP', 'CONVERTED', 'CLOSED']);
export const CONSULTATION_STATUSES = Object.freeze(['NOT_STARTED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED']);
export const CONSULTATION_RESULTS = Object.freeze(['SUCCESS', 'FOLLOW_UP', 'FAIL']);

export const PRODUCT_CATEGORY_SET = new Set(PRODUCT_CATEGORIES);
export const ACTUAL_OPEN_STATUS_SET = new Set(ACTUAL_OPEN_STATUSES);
export const INSTALL_STATUS_SET = new Set(INSTALL_STATUSES);
export const CONTRACT_STATUS_SET = new Set(CONTRACT_STATUSES);
export const LEAD_STATUS_SET = new Set(LEAD_STATUSES);
export const CONSULTATION_STATUS_SET = new Set(CONSULTATION_STATUSES);
export const CONSULTATION_RESULT_SET = new Set(CONSULTATION_RESULTS);
